version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
      - /app/tmp
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=bookstore_go_development
      - DB_PORT=5432

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookstore_go_development
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

